# Generated by Django 3.2.7 on 2021-09-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_users_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='balance',
            field=models.IntegerField(default=999999999),
        ),
        migrations.AddField(
            model_name='users',
            name='contact',
            field=models.IntegerField(default=8888822222),
        ),
        migrations.AddField(
            model_name='users',
            name='email_id',
            field=models.EmailField(default='bonk@gmail.com', max_length=254),
        ),
    ]
