# Generated by Django 3.2.7 on 2021-09-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20210911_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
